# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kitemmodels': '@stable'
    'frameworks/kcontacts': '@stable'
    'frameworks/kirigami': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/kservice': '@stable'
    'frameworks/solid': '@stable'
    'frameworks/kpeople': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/qqc2-desktop-style': '@stable'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/kwayland': '@stable'
    'frameworks/kpackage': '@stable'
    'libraries/pulseaudio-qt/': '@stable'
